### PR TITLE
refactor:AssessmentDTO to use curriculumMembershipId

### PR DESCRIPTION
**Pull request by hihilary**
TIS21-2422

### CODE REVIEW

**Comment by hihilary** [comment]
The Quality Gate failure is due to DTO not covered, which (I think) should be ignored.
image

**Comment by jayanta2018** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130)
> 
> [Bug](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&metric=new_coverage&view=list) [69.2% Coverage](https://sonarcloud.io/component_measures?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=Health-Education-England_TIS-ASSESSMENTS&pullRequest=130&metric=new_duplicated_lines_density&view=list)

Sonar quality gate failed. Just wondering if that is an issue? @hihilary

**Review by jayanta2018 — APPROVED** [review]

**Comment by CaiWillis** [comment]
> The Quality Gate failure is due to DTO not covered, which (I think) should be ignored. image

Not really suggesting you do this because it's probably a can of worms (doing this will probably cause a cascade of breaking stuff), but just wondering if using the lombok autoimplemented getters and setters would fix the test coverage.

A quick glance seems like there's nothing beyond what you'd expect happening with the getters and setters but there's the argument that you _could_ be doing something interesting in them that might need testing therefore should be covered by tests . . .

But yeah this one is probably "safe" to ignore

**Comment by hihilary** [comment]
> > The Quality Gate failure is due to DTO not covered, which (I think) should be ignored. image
> 
> Not really suggesting you do this because it's probably a can of worms (doing this will probably cause a cascade of breaking stuff), but just wondering if using the lombok autoimplemented getters and setters would fix the test coverage as I think they're ignored.
> 
> A quick glance seems like there's nothing beyond what you'd expect happening with the getters and setters but there's the argument that you _could_ be doing something interesting in them that might need testing therefore should be covered by tests . . .
> 
> But yeah this one is probably "safe" to ignore

Really good point, I think I will merge this one first, then raise a new PR to try the lombok config.

**Pull request merged**
